import type { ProviderProfile, WorkflowDefinition, WorkflowStage } from '../contracts';
import { defaultPromptTemplates } from './defaultPromptTemplates';

export const providers: ProviderProfile[] = [
  { id: 'openai-compatible', name: '文本接口', kind: 'openai-compatible', template_id: 'openai-compatible-text', base_url: '', api_key_env: 'NOVEL_LLM_API_KEY', default_model: 'gpt-4.1-mini', model_options: ['gpt-4.1-mini'], is_global_default: true, enabled: true },
  { id: 'openai-compatible-image', name: '图片接口', kind: 'openai-compatible-image', template_id: 'openai-compatible-image', base_url: '', api_key_env: 'NOVEL_IMAGE_API_KEY', default_model: 'gpt-image-1.5', model_options: ['gpt-image-1.5'], is_global_default: true, enabled: true },
];

export const prompts = defaultPromptTemplates;

const baseModel = { model: 'gpt-4.1-mini', temperature: 0.7, max_tokens: 2600, top_p: 0.95, timeout_seconds: 120 };
const baseQuality = { min_score: 0.8, retry_on_fail: true, require_human_review: false, checks: [] as string[] };

const generationBudgets = {
  info: { target_chars: 2200, min_chars: 1400, max_chars: 3200, max_tokens: 4600, description: '立项 Story Brief：建立完整人物基线、阵营关系与风格规格，同时保持可人工定稿。' },
  summary: { target_chars: 1200, min_chars: 1200, max_chars: 2800, max_tokens: 3600, description: '完整全书梗概：覆盖完整故事、人物变化与结局承诺。' },
  outline: { target_chars: 1400, min_chars: 1400, max_chars: 3600, max_tokens: 4200, description: '分卷 beat board：字段完整，不从自由文本二次拆节拍。' },
  detail: { target_chars: 1800, min_chars: 1800, max_chars: 4800, max_tokens: 5200, description: '三章施工细纲：覆盖 POV、目标、冲突、事实、伏笔、人物变化。' },
  text: { target_chars: 1500, min_chars: 1500, max_chars: 3200, max_tokens: 4200, description: '单章正文：真实 API 首轮默认生成前 3 章。' },
  cover: { target_chars: 500, min_chars: 500, max_chars: 1400, max_tokens: 2200, description: '封面 brief/prompt 与视觉候选。' },
};

const baseVariant = { enabled: false, candidate_count: 1, judge_provider_profile_id: 'inherit', judge_model: 'gpt-4.1-mini', dimensions: ['连续性', '人物一致性', '伏笔推进', '语言质感', '模板味'], retry_on_fail: false };
const outputSchemas = {
  info: {
    selected_title: 'string',
    title_candidates: 'string[]',
    synopsis: 'string',
    worldbuilding_detail: 'string',
    characters: 'Array<{ name, identity, background, motivation, relations, tier, faction, faction_stance, growth_direction }>',
    relationships: 'Array<{ source, target, relation, kind, polarity, strength }>',
    tags: 'string[]',
    downstream_constraints: 'string[]',
    risk_notes: 'string[]',
    voice_spec: '{ narration, rhythm, banned_words[], cliche_slots[], per_character[] }',
  },
  summary: {
    one_liner: 'string',
    full_synopsis: 'string',
    act_structure: 'Array<{ title, goal, turn }>',
    core_conflict: 'string',
    character_arcs: 'Array<{ name, arc, pressure, next }>',
    key_turns: 'Array<{ label, detail }>',
    ending_resolution: 'string',
    consistency_checks: 'string[]',
  },
  outline: {
    volumes: 'Array<{ title, chapter_range, volume_goal, rhythm, opening, development, midpoint, climax, resolution, new_characters, character_progression, world_reveal, foreshadow_plan }>',
  },
  detail: {
    chapters: 'Array<{ chapter, pov, scene, goal, entry_state, conflict, stakes, fact_reveals, foreshadow, character_shift, hook, continuity_notes, wiki_candidates, new_npcs }>',
  },
  text: {
    schema_version: 'number',
    status: 'running|completed',
    target_chapters: 'number',
    context_packet: 'ChapterContextPacket',
    context_packets: 'ChapterContextPacket[]',
    chapter_deltas: 'Array<{ chapter, delta }>',
    chapters: 'Array<{ id, title, generated_title, content, words, status, version, commit_signature, summary, summary_dirty, context_packet, wiki_writebacks, character_shift, foreshadow_updates, quality_report, quality_recheck, model_review, writeback_proposal, revision_history, version_history }>',
    quality_reports: 'QualityReport[]',
    wiki_writebacks: 'Array<{ target, fact, claim_key, source_chapter }>',
    chapter_summaries: 'Array<{ chapter, summary }>',
  },
  cover: {
    brief: 'string',
    visual_keywords: 'string[]',
    composition: 'string',
    copy_suggestions: 'string[]',
    prompt: 'string',
    candidates: 'Array<{ id, composition, palette, quality_summary }>',
    selected_candidate_id: 'string',
    asset_generation: '{ status, total, ready_count, failed_count, provider_profile_id, model, size, quality, updated_at }',
  },
  export: {
    manifest: 'Array<{ name, format, status }>',
    formats: 'string[]',
    chapters: 'Array<{ id, title, words, status, content }>',
    metadata: 'Record<string, string>',
    cover_asset: '{ candidate_id, asset_id, sha256, mime_type, width, height, size_bytes, image_url }',
    validation: 'Record<string, string>',
    package_status: '{ kind, name, ready }',
  },
};

export const stages: WorkflowStage[] = [
  {
    id: 'info',
    type: 'info_recommend',
    label: '创作立项定稿',
    params: {},
    input_refs: [],
    output_key: 'info_recommend',
    provider_profile_id: 'openai-compatible',
    model_settings: { ...baseModel, max_tokens: generationBudgets.info.max_tokens },
    prompt_template_id: 'prompt-info',
    input_schema: [
      { key: 'genre', label: '题材', type: 'select', required: true, default: '悬疑', options: ['悬疑', '玄幻', '都市', '科幻', '言情', '历史', '现实', '轻小说'] },
      { key: 'target_length', label: '目标篇幅', type: 'select', required: true, default: '长篇', options: ['短篇', '中篇', '长篇', '系列长篇'] },
      { key: 'target_words_range', label: '目标字数区间', type: 'select', required: true, default: '80-120 万字', options: ['1-3 万字', '5-10 万字', '20-40 万字', '80-120 万字', '120 万字以上'] },
      { key: 'audience', label: '目标读者', type: 'text', required: true, default: '偏好强情节、悬念推进、人物关系清晰的网文读者' },
      { key: 'core_concept', label: '核心创意/冲突', type: 'textarea', required: true, default: '旧港多年前的记忆实验留下旧案回声，主角追查真相时发现自己最可信的记忆也被改写。' },
      { key: 'keywords', label: '关键词', type: 'tags', required: true, default: ['旧港', '记忆实验', '群像', '旧案'] },
      { key: 'taboos', label: '禁忌/不要出现', type: 'textarea', required: true, default: '避免无动机黑化、机械降神、纯设定堆砌、套路化系统开局和无关恋爱线抢主线。' },
      { key: 'reference_mode', label: '参考源模式', type: 'select', required: true, default: 'smart_search', options: ['smart_search', 'url', 'knowledge_base'] },
      { key: 'reference_keywords', label: '参考关键词', type: 'tags', default: ['长篇悬疑', '记忆', '群像', '伏笔'] },
      { key: 'reference_query_intent', label: '参考检索意图', type: 'textarea', default: '检索旧港、记忆实验、群像悬疑结构的参考材料；只提炼结构、节奏、题材约束，不返回可照搬桥段。' },
      { key: 'reference_urls', label: '指定链接', type: 'tags', default: [] },
      { key: 'knowledge_base_doc_ids', label: '知识库文档', type: 'tags', default: [] },
      { key: 'enable_web_search', label: '智能搜索使用联网', type: 'boolean', default: true },
      { key: 'reference_summary', label: '参考资料摘要', type: 'textarea', default: '' },
    ],
    output_schema: outputSchemas.info,
    memory_policy: { read: false, write: true, scope: 'project', kinds: ['worldbuilding', 'topology'] },
    generation_budget: generationBudgets.info,
    variant_policy: { ...baseVariant },
    quality_policy: {
      ...baseQuality,
      min_score: 0.82,
      checks: ['Brief 完整度', '题材匹配', '受众匹配', '世界观可延展性', '参考资料吸收', '禁忌遵守', '模板味风险'],
    },
  },
  {
    id: 'summary',
    type: 'summary',
    label: '全书梗概',
    params: {},
    input_refs: ['info_recommend'],
    output_key: 'summary',
    provider_profile_id: 'openai-compatible',
    model_settings: { ...baseModel, max_tokens: generationBudgets.summary.max_tokens },
    prompt_template_id: 'prompt-summary',
    input_schema: [
      { key: 'target_words', label: '梗概字数', type: 'number', default: 1200 },
      { key: 'structure', label: '结构偏好', type: 'select', default: '起承转合', options: ['起承转合', '三幕式', '悬疑递进', '群像交织'] },
      { key: 'ending_direction', label: '结局方向', type: 'text', default: '真相公开但保留余味' },
    ],
    output_schema: outputSchemas.summary,
    memory_policy: { read: true, write: true, scope: 'project', kinds: ['worldbuilding', 'topology'] },
    generation_budget: generationBudgets.summary,
    variant_policy: { ...baseVariant },
    quality_policy: { ...baseQuality },
  },
  {
    id: 'outline',
    type: 'outline',
    label: '分卷大纲',
    params: {},
    input_refs: ['summary'],
    output_key: 'outline',
    provider_profile_id: 'openai-compatible',
    model_settings: { ...baseModel, max_tokens: generationBudgets.outline.max_tokens },
    prompt_template_id: 'prompt-outline',
    input_schema: [
      { key: 'volume_count', label: '卷数', type: 'number', default: 1 },
      { key: 'chapters_per_volume', label: '每卷章节数', type: 'number', default: 3 },
      { key: 'conflict_density', label: '冲突密度', type: 'select', default: '中高', options: ['平缓', '中等', '中高', '高压'] },
    ],
    output_schema: outputSchemas.outline,
    memory_policy: { read: true, write: true, scope: 'volume', kinds: ['worldbuilding', 'topology', 'outline'] },
    generation_budget: generationBudgets.outline,
    variant_policy: { ...baseVariant },
    quality_policy: { ...baseQuality },
  },
  {
    id: 'detail',
    type: 'detail_outline',
    label: '章节细纲',
    params: {},
    input_refs: ['outline'],
    output_key: 'detail_outline',
    provider_profile_id: 'openai-compatible',
    model_settings: { ...baseModel, max_tokens: generationBudgets.detail.max_tokens },
    prompt_template_id: 'prompt-detail',
    input_schema: [
      { key: 'chapter_count', label: '细纲章节数', type: 'number', default: 3 },
      { key: 'must_include', label: '每章必须包含', type: 'tags', default: ['目标', '冲突', '伏笔', '章末钩子'] },
    ],
    output_schema: outputSchemas.detail,
    memory_policy: { read: true, write: true, scope: 'chapter', kinds: ['worldbuilding', 'topology', 'outline', 'chapter'] },
    generation_budget: generationBudgets.detail,
    variant_policy: { ...baseVariant },
    quality_policy: { ...baseQuality },
  },
  {
    id: 'text',
    type: 'chapter_text',
    label: '正文生成',
    params: {},
    input_refs: ['detail_outline'],
    output_key: 'chapters',
    provider_profile_id: 'openai-compatible',
    model_settings: { ...baseModel, max_tokens: generationBudgets.text.max_tokens, temperature: 0.82 },
    prompt_template_id: 'prompt-text',
    input_schema: [
      { key: 'chapter_words', label: '单章字数', type: 'number', default: 1200 },
      { key: 'pov', label: '叙事视角', type: 'select', default: '第三人称有限视角', options: ['第一人称', '第三人称有限视角', '多视角'] },
      { key: 'batch_generate', label: '批量生成章节', type: 'boolean', default: true },
      { key: 'enable_version_compare', label: '自动版本比对', type: 'boolean', default: false, help: '仅平衡创作开放；精细定稿只在用户主动换稿时生成候选。' },
      { key: 'version_candidate_count', label: '候选版本数', type: 'number', default: 2, help: '仅用于平衡创作自动对比，范围 1-3 版；极速和精细自动链路固定 1 版。' },
      { key: 'judge_provider_profile_id', label: '评审 Provider', type: 'select', default: 'inherit', options: ['inherit', 'openai-compatible'], help: '默认继承正文阶段 Provider。' },
      { key: 'judge_model', label: '评审模型', type: 'text', default: 'gpt-4.1-mini' },
      { key: 'compare_dimensions', label: '比对维度', type: 'tags', default: ['连续性', '人物一致性', '伏笔推进', '语言质感', '模板味'] },
    ],
    output_schema: outputSchemas.text,
    memory_policy: { read: true, write: true, scope: 'chapter', kinds: ['worldbuilding', 'topology', 'outline', 'chapter'] },
    generation_budget: generationBudgets.text,
    variant_policy: { ...baseVariant, enabled: false, candidate_count: 1, retry_on_fail: false },
    quality_policy: { ...baseQuality, min_score: 0.84 },
  },
  {
    id: 'cover',
    type: 'cover_image',
    label: 'AI 封面',
    params: {},
    input_refs: ['info_recommend', 'summary', 'outline', 'detail_outline'],
    output_key: 'cover',
    provider_profile_id: 'openai-compatible',
    image_provider_profile_id: 'openai-compatible-image',
    model_settings: { ...baseModel, model: 'gpt-4.1-mini', max_tokens: generationBudgets.cover.max_tokens },
    prompt_template_id: 'prompt-cover',
    input_schema: [
      { key: 'cover_style', label: '封面风格', type: 'select', default: '电影感悬疑', options: ['电影感悬疑', '国风幻想', '赛博科幻', '青春现实'] },
      { key: 'aspect_ratio', label: '比例', type: 'select', default: '2:3', options: ['2:3'] },
      { key: 'candidate_count', label: '图片候选数', type: 'number', default: 3, help: '每个候选对应一次独立图片生成，范围 1-4。' },
      { key: 'image_quality', label: '图片质量', type: 'select', default: 'medium', options: ['low', 'medium', 'high'] },
      { key: 'asset_retry_limit', label: '失败重试上限', type: 'number', default: 2, help: '仅对失败候选显式重试，范围 0-3。' },
      { key: 'image_budget_usd', label: '图片费用上限（USD）', type: 'number', default: 0, help: '0 表示仅限制调用次数；填写后会在调用前校验预计费用。' },
    ],
    output_schema: outputSchemas.cover,
    memory_policy: { read: false, write: false, scope: 'project', kinds: ['cover'] },
    generation_budget: generationBudgets.cover,
    variant_policy: { ...baseVariant },
    quality_policy: { ...baseQuality, retry_on_fail: false },
  },
  {
    id: 'export',
    type: 'export_artifact',
    label: '导出产物',
    params: {},
    input_refs: ['info_recommend', 'summary', 'outline', 'detail_outline', 'chapters', 'cover'],
    output_key: 'export',
    provider_profile_id: 'openai-compatible',
    model_settings: { ...baseModel },
    prompt_template_id: '',
    input_schema: [{ key: 'export_format', label: '导出格式', type: 'select', default: 'Markdown + JSON', options: ['Markdown + JSON', '纯 Markdown', 'JSON'] }],
    output_schema: outputSchemas.export,
    memory_policy: { read: false, write: false, scope: 'project', kinds: [] },
    variant_policy: { ...baseVariant },
    quality_policy: { ...baseQuality, retry_on_fail: false },
  },
];

export const defaultWorkflow: WorkflowDefinition = {
  id: 'default-novel-workflow',
  name: '全自动长篇小说生成',
  version: '1.0.5-parallel-delivery',
  global_inputs: [
    { key: 'title', label: '项目标题', type: 'text', required: true, default: '雾港旧声' },
  ],
  provider_profiles: providers,
  prompt_templates: prompts,
  stage_configs: {},
  batch_policy: { enabled: false, count: 1, parallelism: 1 },
  quality_mode: 'balanced',
  canvas_layout: {
    nodes: {
      info: { x: 20, y: 168 },
      summary: { x: 214, y: 168 },
      outline: { x: 408, y: 168 },
      detail: { x: 602, y: 168 },
      text: { x: 796, y: 168 },
      cover: { x: 990, y: 168 },
      export: { x: 1184, y: 168 },
      'wiki-layer': { x: 324, y: -96 },
      'quality-layer': { x: 708, y: 452 },
    },
    viewport: { x: 0, y: 0, zoom: 0.76 },
    crosscutting_visible: true,
    locked: false,
  },
  nodes: stages,
  edges: [
    { id: 'e-info-summary', source: 'info', target: 'summary' },
    { id: 'e-summary-outline', source: 'summary', target: 'outline' },
    { id: 'e-outline-detail', source: 'outline', target: 'detail' },
    { id: 'e-detail-text', source: 'detail', target: 'text' },
    { id: 'e-detail-cover', source: 'detail', target: 'cover' },
    { id: 'e-text-export', source: 'text', target: 'export' },
    { id: 'e-cover-export', source: 'cover', target: 'export' },
  ],
};

export const templates = ['全自动长篇小说生成', '短篇投稿生成', '只生成大纲', '批量选题/推荐', '正文续写 + Wiki 约束'];
