import type { ProjectRecord, RunStartInputs, WorkflowDefinition } from '../contracts';
import type { RunSource } from '../lib/runSource';
import { lengthEnvelopeFromStage } from '../lib/narrativeScale';
import { stageInputDefaults } from '../lib/workflow';

type RunProjectContext = Pick<ProjectRecord, 'id'> | null;

function positiveInteger(value: unknown): number | null {
  const numeric = Number(value);
  return Number.isInteger(numeric) && numeric > 0 ? numeric : null;
}

/**
 * A formal book title is generated by the Brief Artifact. Run creation only
 * carries the selected project, the author's idea and deterministic settings.
 */
export function buildRunInputs(
  workflow: WorkflowDefinition,
  runSource: RunSource = 'backend',
  project: RunProjectContext = null,
): RunStartInputs {
  const stageConfigs = Object.fromEntries(workflow.nodes.map((stage) => [stage.id, stageInputDefaults(stage)]));
  const briefStage = workflow.nodes.find((stage) => stage.type === 'brief');
  const briefConfig = briefStage ? { ...stageConfigs[briefStage.id] } : {};
  const lengthEnvelope = briefStage ? lengthEnvelopeFromStage(briefStage) : {
    word_target_soft: 100_000,
  };
  delete briefConfig.word_target_soft;
  const scaleOverrides = {
    turn_target: positiveInteger(briefConfig.turn_target_override),
  };
  delete briefConfig.turn_target_override;
  const exportConfig = stageConfigs.export ?? {};
  return {
    project_id: project?.id ?? '',
    quality_mode: workflow.quality_mode,
    length_envelope: lengthEnvelope,
    scale_overrides: scaleOverrides,
    run_intent: {
      project_brief: {
        genre: briefConfig.genre,
        audience: briefConfig.audience,
        narrative_profile: briefConfig.narrative_profile,
        core_concept: briefConfig.core_concept,
        keywords: briefConfig.keywords,
        taboos: briefConfig.taboos,
      },
      knowledge_strategy: {
        reference_mode: briefConfig.reference_mode,
        reference_keywords: briefConfig.reference_keywords,
        reference_query_intent: briefConfig.reference_query_intent,
        reference_urls: briefConfig.reference_urls,
        knowledge_base_doc_ids: briefConfig.knowledge_base_doc_ids,
        enable_web_search: briefConfig.enable_web_search,
        reference_summary: briefConfig.reference_summary,
      },
    },
    export_preferences: {
      format: String(exportConfig.export_format) as 'md' | 'json' | 'zip',
      author: String(exportConfig.author ?? ''),
      version_note: String(exportConfig.version_note ?? ''),
    },
  };
}
