import { Plus, Trash2 } from 'lucide-react';
import type { CharacterBibleArtifact, CharacterRelation } from './characterBibleArtifact';

type Props = { artifact: CharacterBibleArtifact; onChange: (artifact: CharacterBibleArtifact) => void; readOnly: boolean };

export function CharacterRelationshipSection({ artifact, onChange, readOnly }: Props) {
  const updateRelation = (index: number, patch: Partial<CharacterRelation>) => onChange({ ...artifact, relations: artifact.relations.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) });
  const addRelation = () => onChange({ ...artifact, relations: [...artifact.relations, { a: artifact.subjects[0]?.id ?? '', b: artifact.subjects[1]?.id ?? '', type: '待补充', pressure: '待补充' }] });
  return <section className="character-bible-section character-relationship-section"><header><div><span>关系矩阵</span><strong>{artifact.relations.length} 组关系压力</strong></div>{!readOnly && artifact.subjects.length > 1 ? <button className="character-section-command" onClick={addRelation} type="button"><Plus size={15} />新增关系</button> : null}</header><div className="character-relationship-table" role="table"><div className="character-relationship-head" role="row"><span>主体 A</span><span>主体 B</span><span>关系类型</span><span>压力源</span><span /></div>{artifact.relations.map((relation, index) => <div className="character-relationship-row" key={`${relation.a}-${relation.b}-${index}`} role="row"><SubjectSelect artifact={artifact} onChange={(a) => updateRelation(index, { a })} readOnly={readOnly} value={relation.a} /><SubjectSelect artifact={artifact} onChange={(b) => updateRelation(index, { b })} readOnly={readOnly} value={relation.b} /><input aria-label="关系类型" onChange={(event) => updateRelation(index, { type: event.target.value })} readOnly={readOnly} value={relation.type} /><input aria-label="关系压力源" onChange={(event) => updateRelation(index, { pressure: event.target.value })} readOnly={readOnly} value={relation.pressure} />{!readOnly ? <button aria-label="删除关系" onClick={() => onChange({ ...artifact, relations: artifact.relations.filter((_, itemIndex) => itemIndex !== index) })} title="删除关系" type="button"><Trash2 size={15} /></button> : <span />}</div>)}{!artifact.relations.length ? <p className="character-table-empty">当前没有关系边</p> : null}</div></section>;
}

function SubjectSelect({ artifact, onChange, readOnly, value }: { artifact: CharacterBibleArtifact; onChange: (value: string) => void; readOnly: boolean; value: string }) { return <select aria-label="关系主体" disabled={readOnly} onChange={(event) => onChange(event.target.value)} value={value}><option value="">未选择</option>{artifact.subjects.map((subject) => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select>; }
