import { Fingerprint } from 'lucide-react';
import { CharacterChapterWindowField } from './CharacterChapterWindowField';
import type { CharacterBibleArtifact, CharacterKind, CharacterSubject } from './characterBibleArtifact';

type Props = { artifact: CharacterBibleArtifact; onChange: (artifact: CharacterBibleArtifact) => void; readOnly: boolean; subject: CharacterSubject; totalChapters?: number };
const KIND_LABELS: Record<CharacterKind, string> = { protagonist: '主角', major: '重要配角', functional: '功能角色', npc: 'NPC', historical_record: '历史主体' };

export function CharacterDossierEditor({ artifact, onChange, readOnly, subject, totalChapters }: Props) {
  const update = (patch: Partial<CharacterSubject>) => onChange({ ...artifact, subjects: artifact.subjects.map((item) => item.id === subject.id ? { ...item, ...patch } : item) });
  return <section className="character-dossier-editor"><header className="character-dossier-heading"><div><span>聚焦档案</span><strong>{subject.name}</strong></div><div className="character-stable-id"><Fingerprint size={14} /><code>{subject.id}</code></div></header><div className="character-identity-grid"><label><span>姓名</span><input aria-label="主体姓名" onChange={(event) => update({ name: event.target.value })} readOnly={readOnly} value={subject.name} /></label><label><span>主体类型</span><select aria-label="主体类型" disabled={readOnly} onChange={(event) => update({ kind: event.target.value as CharacterKind })} value={subject.kind}>{Object.entries(KIND_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><CharacterChapterWindowField label="首次出现窗口" onChange={(debut) => update({ debut })} readOnly={readOnly} totalChapters={totalChapters} value={subject.debut} /></div><div className="character-motive-grid"><CharacterField label="叙事职责" onChange={(value) => update({ function: value })} readOnly={readOnly} value={subject.function} /><CharacterField label="行动驱力" onChange={(drive) => update({ drive })} readOnly={readOnly} value={subject.drive} /><CharacterField label="必要变化" onChange={(change) => update({ change })} readOnly={readOnly} value={subject.change} /></div><label className="character-boundaries-field"><span>使用限制</span><textarea onChange={(event) => update({ limits: splitValues(event.target.value) })} readOnly={readOnly} rows={3} value={subject.limits.join('\n')} /></label><label className="character-boundaries-field"><span>职责需求引用</span><textarea onChange={(event) => update({ demand_refs: splitValues(event.target.value) })} readOnly={readOnly} rows={3} value={subject.demand_refs.join('\n')} /></label></section>;
}

function CharacterField({ label, onChange, readOnly, value }: { label: string; onChange: (value: string) => void; readOnly: boolean; value: string }) { return <label><span>{label}</span><textarea onChange={(event) => onChange(event.target.value)} readOnly={readOnly} rows={3} value={value} /></label>; }
function splitValues(value: string) { return value.split(/[；;\n]/).map((item) => item.trim()).filter(Boolean); }
