from __future__ import annotations

from novel_workflow.providers.template_contract import (
    ModelCapabilityProfile,
    ProviderTemplate,
)

from novel_workflow.providers.gateway_text_templates import (
    GATEWAY_TEXT_PROVIDER_TEMPLATES,
)
from novel_workflow.providers.tokenhub_text_template import (
    TOKENHUB_TEXT_PROVIDER_TEMPLATE,
)


COMPATIBLE_VENDOR_TEXT_PROVIDER_TEMPLATES = (
    ProviderTemplate(
        id="openai-compatible-text",
        label="通用 OpenAI 兼容文本",
        kind="openai-compatible",
        base_url="",
        default_model="",
        api_key_env="NOVEL_LLM_API_KEY",
        docs_url="https://platform.openai.com/docs/api-reference/chat",
        integration_tier="custom",
        description="适合自建服务或尚未收录的 OpenAI Chat Completions 兼容接口。",
        supports_response_format=False,
        structured_output_mode="prompt_only",
        requires_json_keyword=True,
        requires_json_example=True,
        structured_output_notes="未知上游不静态发送 response_format；使用 JSON 示例与本地合同校验。",
    ),
    TOKENHUB_TEXT_PROVIDER_TEMPLATE,
    ProviderTemplate(
        id="siliconflow-text",
        label="SiliconFlow 文本",
        kind="openai-compatible",
        base_url="https://api.siliconflow.cn/v1",
        default_model="Qwen/Qwen3-8B",
        model_options=["Qwen/Qwen3-8B"],
        api_key_env="SILICONFLOW_API_KEY",
        docs_url="https://docs.siliconflow.cn/en/userguide/guides/json-mode",
        description="SiliconFlow 官方 OpenAI 兼容文本接口。",
        structured_output_mode="json_object",
        requires_json_keyword=True,
        requires_json_example=True,
        structured_output_notes="当前公开合同使用 json_object；模型清单可能变化，最终仍执行本地合同校验。",
    ),
    ProviderTemplate(
        id="openrouter-text",
        label="OpenRouter 文本路由",
        kind="openai-compatible",
        base_url="https://openrouter.ai/api/v1",
        default_model="openai/gpt-4.1-mini",
        model_options=["openai/gpt-4.1-mini"],
        api_key_env="OPENROUTER_API_KEY",
        docs_url="https://openrouter.ai/docs/guides/features/structured-outputs",
        capability_docs=[
            "https://openrouter.ai/docs/guides/routing/provider-selection",
        ],
        integration_tier="gateway",
        description="OpenRouter 聚合路由；能力与参数必须以所选上游模型目录为准。",
        structured_output_mode="json_schema",
        supports_json_schema=True,
        schema_transform="openai_subset",
        json_schema_strict=True,
        extra_body_parameters={
            "provider": {
                "require_parameters": True,
                "allow_fallbacks": False,
            }
        },
        discovers_model_parameters=True,
        required_model_parameter_any_of=["structured_outputs", "response_format"],
        structured_output_notes="要求路由上游支持全部请求参数并关闭网关隐式回退；若无兼容上游则显式失败，由本地预算链决定是否换 Provider。",
    ),
    ProviderTemplate(
        id="volcengine-ark-text",
        label="火山方舟文本",
        kind="openai-compatible",
        base_url="https://ark.cn-beijing.volces.com/api/v3",
        default_model="",
        api_key_env="ARK_API_KEY",
        docs_url="https://www.volcengine.com/docs/82379/1182403",
        description="火山方舟 OpenAI 兼容入口；模型填写已部署的推理接入点 ID。",
        supports_response_format=False,
        structured_output_mode="prompt_only",
        requires_json_keyword=True,
        requires_json_example=True,
        structured_output_notes="部署 Endpoint 的能力由具体模型决定；模板不静态声明 response_format。",
    ),
    ProviderTemplate(
        id="groq-text",
        label="Groq 文本",
        kind="openai-compatible",
        base_url="https://api.groq.com/openai/v1",
        default_model="openai/gpt-oss-120b",
        model_options=["openai/gpt-oss-120b", "openai/gpt-oss-20b", "qwen/qwen3.6-27b"],
        api_key_env="GROQ_API_KEY",
        docs_url="https://console.groq.com/docs/structured-outputs",
        capability_docs=[
            "https://console.groq.com/docs/prompt-caching",
        ],
        integration_tier="compatibility",
        description="Groq 官方 OpenAI 兼容层；字段能力以具体模型为准。",
        max_tokens_field="max_completion_tokens",
        structured_output_mode="json_object",
        requires_json_keyword=True,
        model_capabilities=[
            ModelCapabilityProfile(
                model_pattern="openai/gpt-oss-*",
                capability_docs=[
                    "https://console.groq.com/docs/structured-outputs",
                    "https://console.groq.com/docs/reasoning",
                ],
                structured_output_mode="json_schema",
                supports_json_schema=True,
                schema_transform="openai_subset",
                json_schema_strict=True,
                sampling_parameter_mode="none",
                stage_request_parameters={
                    "spine": {"reasoning_effort": "low"},
                    "cast": {"reasoning_effort": "high"},
                    "detail": {"reasoning_effort": "high"},
                    "text.review": {"reasoning_effort": "high"},
                },
            ),
            ModelCapabilityProfile(
                model_pattern="qwen/qwen3.6-27b*",
                capability_docs=["https://console.groq.com/docs/model/qwen/qwen3.6-27b"],
                stage_request_parameters={
                    "brief": {
                        "reasoning_effort": "default",
                        "reasoning_format": "hidden",
                    },
                    "spine": {"reasoning_effort": "none"},
                    "cast": {
                        "reasoning_effort": "default",
                        "reasoning_format": "hidden",
                    },
                    "volumes": {
                        "reasoning_effort": "default",
                        "reasoning_format": "hidden",
                    },
                    "detail": {
                        "reasoning_effort": "default",
                        "reasoning_format": "hidden",
                    },
                    "text": {"reasoning_effort": "none"},
                    "text.evidence": {"reasoning_effort": "none"},
                    "text.review": {
                        "reasoning_effort": "default",
                        "reasoning_format": "hidden",
                    },
                },
            ),
        ],
        structured_output_notes="GPT-OSS 使用 strict JSON Schema；Qwen 3.6 使用 JSON Object，并在推理阶段隐藏 reasoning channel。",
    ),
    ProviderTemplate(
        id="together-text",
        label="Together AI 文本",
        kind="openai-compatible",
        base_url="https://api.together.ai/v1",
        default_model="openai/gpt-oss-120b",
        model_options=["openai/gpt-oss-120b"],
        api_key_env="TOGETHER_API_KEY",
        docs_url="https://docs.together.ai/docs/inference/chat/structured-outputs",
        integration_tier="compatibility",
        description="Together AI 官方 OpenAI 兼容文本入口。",
        structured_output_mode="json_schema",
        supports_json_schema=True,
        schema_transform="openai_subset",
        requires_json_keyword=True,
        requires_json_example=True,
        requires_schema_definition=True,
        model_capabilities=[
            ModelCapabilityProfile(
                model_pattern="openai/gpt-oss-*",
                capability_docs=["https://docs.together.ai/docs/inference/chat/reasoning"],
                sampling_parameter_mode="none",
                stage_request_parameters={
                    "brief": {"reasoning_effort": "medium"},
                    "spine": {"reasoning_effort": "low"},
                    "cast": {"reasoning_effort": "high"},
                    "volumes": {"reasoning_effort": "medium"},
                    "detail": {"reasoning_effort": "high"},
                    "text": {"reasoning_effort": "low"},
                    "text.evidence": {"reasoning_effort": "low"},
                    "text.review": {"reasoning_effort": "high"},
                },
            ),
        ],
        structured_output_notes="Schema 同时进入 Prompt 与 response_format；GPT-OSS 按阶段发送 reasoning_effort，模型支持范围以实时目录为准。",
    ),
    ProviderTemplate(
        id="xai-text",
        label="xAI Grok 文本",
        kind="openai-compatible",
        base_url="https://api.x.ai/v1",
        default_model="grok-4.5",
        model_options=["grok-4.5"],
        api_key_env="XAI_API_KEY",
        docs_url="https://docs.x.ai/developers/model-capabilities/text/structured-outputs",
        capability_docs=[
            "https://docs.x.ai/developers/model-capabilities/text/reasoning",
        ],
        description="xAI 官方 OpenAI 兼容 Chat Completions 接口。",
        structured_output_mode="json_schema",
        supports_json_schema=True,
        schema_transform="openai_subset",
        json_schema_strict=True,
        sampling_parameter_mode="none",
        supports_prompt_cache_key=True,
        prompt_cache_key_header="x-grok-conv-id",
        stage_request_parameters={
            "brief": {"reasoning_effort": "medium"},
            "spine": {"reasoning_effort": "low"},
            "cast": {"reasoning_effort": "high"},
            "volumes": {"reasoning_effort": "medium"},
            "detail": {"reasoning_effort": "high"},
            "text": {"reasoning_effort": "low"},
            "text.evidence": {"reasoning_effort": "low"},
            "text.review": {"reasoning_effort": "high"},
        },
        structured_output_notes="Grok 4.5 使用 JSON Schema；Chat Completions 的稳定缓存键通过 x-grok-conv-id 请求头发送，本地仍校验完整 Pydantic 约束。",
    ),
    ProviderTemplate(
        id="mistral-text",
        label="Mistral AI 文本",
        kind="openai-compatible",
        base_url="https://api.mistral.ai/v1",
        default_model="mistral-large-latest",
        model_options=["mistral-large-latest", "mistral-small-latest"],
        api_key_env="MISTRAL_API_KEY",
        docs_url="https://docs.mistral.ai/api/endpoint/chat",
        capability_docs=[
            "https://docs.mistral.ai/studio-api/conversations/structured-output",
        ],
        integration_tier="compatibility",
        description="Mistral 官方 OpenAI 请求结构兼容入口。",
        structured_output_mode="json_schema",
        supports_json_schema=True,
        schema_transform="openai_subset",
        requires_json_keyword=True,
        assistant_prefill_mode="assistant_prefix",
        assistant_prefill_tasks=["text"],
        assistant_prefill_model_patterns=["mistral-*"],
        supports_prompt_cache_key=True,
        structured_output_notes="优先自定义 JSON Schema；Prefix 只允许显式纯文本正文；同一 Run/阶段使用散列 prompt_cache_key。",
    ),
    ProviderTemplate(
        id="fireworks-text",
        label="Fireworks AI 文本",
        kind="openai-compatible",
        base_url="https://api.fireworks.ai/inference/v1",
        default_model="accounts/fireworks/models/gpt-oss-120b",
        model_options=["accounts/fireworks/models/gpt-oss-120b"],
        api_key_env="FIREWORKS_API_KEY",
        docs_url="https://docs.fireworks.ai/structured-responses/structured-response-formatting",
        integration_tier="compatibility",
        description="Fireworks 官方 OpenAI 兼容文本入口；图片协议不混入本模板。",
        structured_output_mode="json_schema",
        supports_json_schema=True,
        schema_transform="openai_subset",
        requires_json_keyword=True,
        requires_json_example=True,
        requires_schema_definition=True,
        structured_output_notes="JSON Schema 会关闭 reasoning 输出；小说结构节点优先保证 Artifact 合同。",
    ),
    ProviderTemplate(
        id="cerebras-text",
        label="Cerebras 文本",
        kind="openai-compatible",
        base_url="https://api.cerebras.ai/v1",
        default_model="gpt-oss-120b",
        model_options=["gpt-oss-120b"],
        api_key_env="CEREBRAS_API_KEY",
        docs_url="https://inference-docs.cerebras.ai/capabilities/structured-outputs",
        integration_tier="compatibility",
        description="Cerebras 官方 OpenAI 兼容入口；角色与参数能力以模型目录为准。",
        structured_output_mode="json_schema",
        supports_json_schema=True,
        schema_transform="openai_subset",
        json_schema_strict=True,
        sampling_parameter_mode="none",
        stage_request_parameters={
            "spine": {"reasoning_effort": "low"},
            "cast": {"reasoning_effort": "high"},
            "detail": {"reasoning_effort": "high"},
            "text.review": {"reasoning_effort": "high"},
        },
        schema_max_chars=5000,
        schema_max_depth=10,
        schema_max_properties=500,
        schema_max_enum_values=500,
        structured_output_notes="GPT-OSS 120B 使用 strict JSON Schema；嵌套对象在请求前统一关闭 additionalProperties。",
    ),
)

COMPATIBLE_TEXT_PROVIDER_TEMPLATES = (
    *COMPATIBLE_VENDOR_TEXT_PROVIDER_TEMPLATES,
    *GATEWAY_TEXT_PROVIDER_TEMPLATES,
)
