from __future__ import annotations

from novel_workflow.providers.template_contract import ProviderTemplate


IMAGE_PROVIDER_TEMPLATES = (
    ProviderTemplate(
        id="openai-compatible-image",
        label="通用 OpenAI 兼容图片",
        kind="openai-compatible-image",
        base_url="",
        default_model="",
        api_key_env="NOVEL_IMAGE_API_KEY",
        docs_url="https://platform.openai.com/docs/api-reference/images",
        integration_tier="custom",
        description="适合实现 /images/generations 的 OpenAI 兼容图片服务。",
    ),
    ProviderTemplate(
        id="openai-image",
        label="OpenAI 图片",
        kind="openai-compatible-image",
        base_url="https://api.openai.com/v1",
        default_model="gpt-image-1.5",
        model_options=["gpt-image-1.5", "gpt-image-1", "gpt-image-1-mini"],
        api_key_env="OPENAI_API_KEY",
        docs_url="https://platform.openai.com/docs/api-reference/images",
        description="OpenAI 官方 Images API。",
    ),
    ProviderTemplate(
        id="tokenhub-hunyuan-image",
        label="腾讯 TokenHub 混元生图",
        kind="openai-compatible-image",
        base_url="https://tokenhub.tencentmaas.com/v1",
        default_model="hy-image-v3.0",
        model_options=["hy-image-v3.0"],
        api_key_env="NOVEL_IMAGE_API_KEY",
        docs_url="https://cloud.tencent.com/document/product/1668/129429",
        description="TokenHub 混元同步生图；尺寸使用冒号且数量字段为 images。",
        image_size_separator=":",
        image_count_field="images",
        supports_image_quality=False,
    ),
    ProviderTemplate(
        id="zhipu-cogview-image",
        label="智谱 CogView 图片",
        kind="openai-compatible-image",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        default_model="cogView-4-250304",
        model_options=["cogView-4-250304", "cogview-4", "glm-image"],
        api_key_env="ZHIPUAI_API_KEY",
        docs_url="https://docs.bigmodel.cn/cn/guide/models/image-generation/cogview-4",
        description="智谱 CogView 同步图片接口。",
        image_count_field="none",
    ),
    ProviderTemplate(
        id="siliconflow-image",
        label="SiliconFlow 图片",
        kind="openai-compatible-image",
        base_url="https://api.siliconflow.cn/v1",
        default_model="Kwai-Kolors/Kolors",
        model_options=["Kwai-Kolors/Kolors"],
        api_key_env="SILICONFLOW_API_KEY",
        docs_url="https://docs.siliconflow.cn/cn/api-reference/images/images-generations",
        description="SiliconFlow 图片接口；使用 image_size 并从 images[] 读取结果。",
        image_size_field="image_size",
        image_count_field="none",
        image_response_field="images",
        supports_image_quality=False,
    ),
    ProviderTemplate(
        id="openrouter-image",
        label="OpenRouter 图片路由",
        kind="openai-compatible-image",
        base_url="https://openrouter.ai/api/v1",
        default_model="",
        api_key_env="OPENROUTER_API_KEY",
        docs_url="https://openrouter.ai/docs/features/multimodal/image-generation",
        integration_tier="gateway",
        description="OpenRouter 独立图片端点；模型需从图片模型目录选择。",
        image_size_field="resolution",
        image_endpoint_path="/images",
        models_endpoint_path="/images/models",
    ),
    ProviderTemplate(
        id="xai-image",
        label="xAI Grok Imagine 图片",
        kind="openai-compatible-image",
        base_url="https://api.x.ai/v1",
        default_model="grok-imagine-image",
        model_options=["grok-imagine-image"],
        api_key_env="XAI_API_KEY",
        docs_url="https://docs.x.ai/developers/model-capabilities/images/generation",
        description="xAI 官方图片端点；产品尺寸会转换为宽高比并请求 1k Base64 结果。",
        image_size_field="aspect_ratio",
        image_static_parameters={"resolution": "1k", "response_format": "b64_json"},
        supports_image_quality=False,
    ),
    ProviderTemplate(
        id="together-image",
        label="Together AI 图片",
        kind="openai-compatible-image",
        base_url="https://api.together.ai/v1",
        default_model="google/imagen-4.0-fast",
        model_options=[
            "google/imagen-4.0-fast",
            "black-forest-labs/FLUX.1-schnell",
            "Qwen/Qwen-Image-2.0",
        ],
        api_key_env="TOGETHER_API_KEY",
        docs_url="https://docs.together.ai/reference/post-images-generations",
        integration_tier="compatibility",
        description="Together Images API；尺寸拆为 width/height，并请求 PNG Base64 结果。",
        image_size_field="width_height",
        image_static_parameters={"response_format": "base64", "output_format": "png"},
        supports_image_quality=False,
    ),
)
