from __future__ import annotations

from novel_workflow.providers.template_contract import ModelCapabilityProfile, ProviderTemplate

OFFICIAL_GLOBAL_TEXT_PROVIDER_TEMPLATES = (
    ProviderTemplate(
        id="openai-chat",
        label="OpenAI 文本",
        kind="openai-compatible",
        base_url="https://api.openai.com/v1",
        default_model="gpt-5.6-terra",
        model_options=["gpt-5.6-terra", "gpt-5.6-sol", "gpt-5.6-luna"],
        api_key_env="OPENAI_API_KEY",
        docs_url="https://developers.openai.com/api/docs/guides/structured-outputs",
        capability_docs=[
            "https://developers.openai.com/api/docs/guides/reasoning",
            "https://developers.openai.com/api/docs/guides/prompt-caching",
            "https://developers.openai.com/api/docs/models",
        ],
        description="OpenAI 官方 Chat Completions；Terra 平衡质量与成本，Sol 用于高难节点，Luna 用于高频轻量节点。",
        structured_output_mode="json_schema",
        supports_json_schema=True,
        schema_transform="openai_subset",
        json_schema_strict=True,
        max_tokens_field="max_completion_tokens",
        sampling_parameter_mode="none",
        thinking_parameter="reasoning_effort",
        structured_output_notes="请求前把 Pydantic Schema 转为官方支持子集；不兼容时降级 json_object，最终仍执行本地合同校验。",
        stage_request_parameters={
            "info": {"reasoning_effort": "medium"},
            "summary": {"reasoning_effort": "low"},
            "outline": {"reasoning_effort": "medium"},
            "detail": {"reasoning_effort": "high"},
            "text": {"reasoning_effort": "none"},
            "text.evidence": {"reasoning_effort": "low"},
            "text.review": {"reasoning_effort": "high"},
        },
    ),
    ProviderTemplate(
        id="gemini-text",
        label="Google Gemini 文本",
        kind="openai-compatible",
        base_url="https://generativelanguage.googleapis.com/v1beta/openai",
        default_model="gemini-3.6-flash",
        model_options=["gemini-3.6-flash", "gemini-3.5-flash-lite"],
        api_key_env="GEMINI_API_KEY",
        docs_url="https://ai.google.dev/gemini-api/docs/openai",
        capability_docs=[
            "https://ai.google.dev/gemini-api/docs/structured-output",
            "https://ai.google.dev/gemini-api/docs/thinking",
            "https://ai.google.dev/gemini-api/docs/latest-model",
        ],
        integration_tier="compatibility",
        description="Google 官方兼容层；3.6 Flash 负责复杂阶段，Flash-Lite 负责高频结构化任务。",
        structured_output_mode="json_schema",
        supports_json_schema=True,
        schema_transform="openai_subset",
        sampling_parameter_mode="none",
        thinking_parameter="reasoning_effort",
        structured_output_notes="兼容层支持 JSON Schema；请求前执行子集判定，不兼容时直接降级 json_object。",
        stage_request_parameters={
            "info": {"reasoning_effort": "medium"},
            "summary": {"reasoning_effort": "low"},
            "outline": {"reasoning_effort": "medium"},
            "detail": {"reasoning_effort": "high"},
            "text": {"reasoning_effort": "low"},
            "text.evidence": {"reasoning_effort": "low"},
            "text.review": {"reasoning_effort": "high"},
        },
        model_capabilities=[
            ModelCapabilityProfile(
                model_pattern="gemini-3.5-flash-lite*",
                capability_docs=["https://ai.google.dev/gemini-api/docs/latest-model"],
                stage_request_parameters={
                    "summary": {"reasoning_effort": "minimal"},
                    "text.evidence": {"reasoning_effort": "minimal"},
                },
            ),
        ],
    ),
    ProviderTemplate(
        id="anthropic-openai-text",
        label="Anthropic Claude（兼容评估）",
        kind="openai-compatible",
        base_url="https://api.anthropic.com/v1",
        default_model="claude-sonnet-5",
        model_options=["claude-sonnet-5", "claude-opus-5"],
        api_key_env="ANTHROPIC_API_KEY",
        docs_url="https://platform.claude.com/docs/en/cli-sdks-libraries/libraries/openai-sdk",
        capability_docs=[
            "https://platform.claude.com/docs/en/build-with-claude/structured-outputs",
            "https://platform.claude.com/docs/en/build-with-claude/prompt-caching",
            "https://platform.claude.com/docs/en/about-claude/models/whats-new-sonnet-5",
        ],
        integration_tier="compatibility",
        description="OpenAI 兼容层仅用于模型评估；生产结构化链路应使用原生 Claude Structured Outputs。",
        supports_response_format=False,
        structured_output_mode="prompt_only",
        requires_json_keyword=True,
        requires_json_example=True,
        sampling_parameter_mode="none",
        thinking_parameter="native thinking (OpenAI compatibility ignores reasoning_effort)",
        structured_output_notes="兼容层忽略 response_format、strict 与 reasoning_effort；这里只保留 Prompt 约束和本地校验。",
        workflow_execution_allowed=False,
        workflow_execution_policy_note="Anthropic 官方将 OpenAI 兼容层定位为模型评估入口，不建议用于长期生产；请等待原生 Claude Messages + Structured Outputs 适配器。",
    ),
)
