from __future__ import annotations

from novel_workflow.providers.template_contract import ProviderTemplate


TEXT_PROVIDER_TEMPLATES = (
    ProviderTemplate(
        id="openai-compatible-text",
        label="通用 OpenAI 兼容文本",
        kind="openai-compatible",
        base_url="",
        default_model="",
        api_key_env="NOVEL_LLM_API_KEY",
        docs_url="https://platform.openai.com/docs/api-reference/chat",
        integration_tier="custom",
        description="适合自建服务或尚未收录的 OpenAI Chat Completions 兼容接口。",
    ),
    ProviderTemplate(
        id="openai-chat",
        label="OpenAI 文本",
        kind="openai-compatible",
        base_url="https://api.openai.com/v1",
        default_model="gpt-4.1-mini",
        model_options=["gpt-4.1-mini", "gpt-4.1"],
        api_key_env="OPENAI_API_KEY",
        docs_url="https://platform.openai.com/docs/api-reference/chat",
        description="OpenAI 官方 Chat Completions 接口。",
    ),
    ProviderTemplate(
        id="tokenhub-text",
        label="腾讯 TokenHub 文本",
        kind="openai-compatible",
        base_url="https://tokenhub.tencentmaas.com/v1",
        default_model="deepseek-v4-pro-202606",
        model_options=["deepseek-v4-pro-202606"],
        api_key_env="NOVEL_LLM_API_KEY",
        docs_url="https://cloud.tencent.com/document/product/1823",
        description="腾讯混元 TokenHub 的 OpenAI 兼容文本入口。",
    ),
    ProviderTemplate(
        id="deepseek-text",
        label="DeepSeek 官方文本",
        kind="openai-compatible",
        base_url="https://api.deepseek.com/v1",
        default_model="deepseek-v4-pro",
        model_options=["deepseek-v4-pro", "deepseek-v4-flash"],
        api_key_env="DEEPSEEK_API_KEY",
        docs_url="https://api-docs.deepseek.com/",
        description="DeepSeek 官方 OpenAI 兼容接口。",
    ),
    ProviderTemplate(
        id="dashscope-text",
        label="阿里云百炼文本",
        kind="openai-compatible",
        base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        default_model="qwen-plus",
        model_options=["qwen-plus", "qwen-max"],
        api_key_env="DASHSCOPE_API_KEY",
        docs_url="https://help.aliyun.com/zh/model-studio/compatibility-of-openai-with-dashscope",
        description="阿里云百炼 OpenAI 兼容模式；海外地域需按官方文档更换 Base URL。",
    ),
    ProviderTemplate(
        id="siliconflow-text",
        label="SiliconFlow 文本",
        kind="openai-compatible",
        base_url="https://api.siliconflow.cn/v1",
        default_model="Qwen/Qwen3-8B",
        model_options=["Qwen/Qwen3-8B"],
        api_key_env="SILICONFLOW_API_KEY",
        docs_url="https://docs.siliconflow.cn/cn/userguide/quickstart",
        description="SiliconFlow 官方 OpenAI 兼容文本接口。",
    ),
    ProviderTemplate(
        id="moonshot-text",
        label="Kimi / Moonshot 文本",
        kind="openai-compatible",
        base_url="https://api.moonshot.cn/v1",
        default_model="kimi-k3",
        model_options=["kimi-k3"],
        api_key_env="MOONSHOT_API_KEY",
        docs_url="https://platform.kimi.com/docs/overview",
        description="Kimi 开放平台的 OpenAI 兼容文本入口。",
    ),
    ProviderTemplate(
        id="zhipu-text",
        label="智谱 GLM 文本",
        kind="openai-compatible",
        base_url="https://open.bigmodel.cn/api/paas/v4",
        default_model="glm-5.2",
        model_options=["glm-5.2"],
        api_key_env="ZHIPUAI_API_KEY",
        docs_url="https://docs.bigmodel.cn/cn/guide/develop/openai/introduction",
        description="智谱 BigModel 的 OpenAI SDK 兼容入口。",
    ),
    ProviderTemplate(
        id="openrouter-text",
        label="OpenRouter 文本路由",
        kind="openai-compatible",
        base_url="https://openrouter.ai/api/v1",
        default_model="openai/gpt-4.1-mini",
        model_options=["openai/gpt-4.1-mini"],
        api_key_env="OPENROUTER_API_KEY",
        docs_url="https://openrouter.ai/docs/quickstart",
        integration_tier="gateway",
        description="OpenRouter 聚合路由；模型、价格和可用区由上游目录决定。",
    ),
    ProviderTemplate(
        id="volcengine-ark-text",
        label="火山方舟文本",
        kind="openai-compatible",
        base_url="https://ark.cn-beijing.volces.com/api/v3",
        default_model="",
        api_key_env="ARK_API_KEY",
        docs_url="https://www.volcengine.com/docs/82379/1182403",
        description="火山方舟 OpenAI 兼容入口；模型填写已部署的推理接入点 ID。",
    ),
    ProviderTemplate(
        id="gemini-text",
        label="Google Gemini 文本",
        kind="openai-compatible",
        base_url="https://generativelanguage.googleapis.com/v1beta/openai",
        default_model="gemini-3.5-flash",
        model_options=["gemini-3.5-flash", "gemini-3.5-pro"],
        api_key_env="GEMINI_API_KEY",
        docs_url="https://ai.google.dev/gemini-api/docs/openai",
        integration_tier="compatibility",
        description="Google 官方兼容层，适合当前结构化文本链路；不包含 File API 与 Grounding 等原生能力。",
    ),
    ProviderTemplate(
        id="groq-text",
        label="Groq 文本",
        kind="openai-compatible",
        base_url="https://api.groq.com/openai/v1",
        default_model="openai/gpt-oss-120b",
        model_options=["openai/gpt-oss-120b", "llama-3.3-70b-versatile", "llama-3.1-8b-instant"],
        api_key_env="GROQ_API_KEY",
        docs_url="https://console.groq.com/docs/openai",
        integration_tier="compatibility",
        description="Groq 官方 OpenAI 兼容层；部分 OpenAI 参数不受支持。",
    ),
    ProviderTemplate(
        id="together-text",
        label="Together AI 文本",
        kind="openai-compatible",
        base_url="https://api.together.ai/v1",
        default_model="openai/gpt-oss-120b",
        model_options=["openai/gpt-oss-120b"],
        api_key_env="TOGETHER_API_KEY",
        docs_url="https://docs.together.ai/docs/inference/openai-compatibility",
        integration_tier="compatibility",
        description="Together AI 官方 OpenAI 兼容文本入口。",
    ),
    ProviderTemplate(
        id="xai-text",
        label="xAI Grok 文本",
        kind="openai-compatible",
        base_url="https://api.x.ai/v1",
        default_model="grok-4.5",
        model_options=["grok-4.5"],
        api_key_env="XAI_API_KEY",
        docs_url="https://docs.x.ai/developers/rest-api-reference/inference/chat",
        description="xAI 官方 OpenAI 兼容 Chat Completions 接口。",
    ),
    ProviderTemplate(
        id="mistral-text",
        label="Mistral AI 文本",
        kind="openai-compatible",
        base_url="https://api.mistral.ai/v1",
        default_model="mistral-large-latest",
        model_options=["mistral-large-latest", "mistral-small-latest"],
        api_key_env="MISTRAL_API_KEY",
        docs_url="https://docs.mistral.ai/resources/migration-guides",
        integration_tier="compatibility",
        description="Mistral 官方 OpenAI 请求结构兼容入口。",
    ),
    ProviderTemplate(
        id="fireworks-text",
        label="Fireworks AI 文本",
        kind="openai-compatible",
        base_url="https://api.fireworks.ai/inference/v1",
        default_model="accounts/fireworks/models/gpt-oss-120b",
        model_options=["accounts/fireworks/models/gpt-oss-120b"],
        api_key_env="FIREWORKS_API_KEY",
        docs_url="https://docs.fireworks.ai/tools-sdks/openai-compatibility",
        integration_tier="compatibility",
        description="Fireworks 官方 OpenAI 兼容文本入口；图片使用不同工作流协议，未混入本模板。",
    ),
    ProviderTemplate(
        id="cerebras-text",
        label="Cerebras 文本",
        kind="openai-compatible",
        base_url="https://api.cerebras.ai/v1",
        default_model="gpt-oss-120b",
        model_options=["gpt-oss-120b"],
        api_key_env="CEREBRAS_API_KEY",
        docs_url="https://inference-docs.cerebras.ai/resources/openai",
        integration_tier="compatibility",
        description="Cerebras 官方 OpenAI 兼容入口；参数和角色支持以模型目录为准。",
    ),
    ProviderTemplate(
        id="anthropic-openai-text",
        label="Anthropic Claude（兼容评估）",
        kind="openai-compatible",
        base_url="https://api.anthropic.com/v1",
        default_model="claude-sonnet-4-6",
        model_options=["claude-sonnet-4-6", "claude-opus-4-6"],
        api_key_env="ANTHROPIC_API_KEY",
        docs_url="https://platform.claude.com/docs/en/cli-sdks-libraries/libraries/openai-sdk",
        integration_tier="compatibility",
        description="官方仅建议用于测试和模型比较；response_format 会被忽略，生产接入应优先原生 Claude 适配器。",
        supports_response_format=False,
    ),
    ProviderTemplate(
        id="litellm-proxy-text",
        label="LiteLLM Proxy",
        kind="openai-compatible",
        base_url="",
        default_model="",
        api_key_env="LITELLM_API_KEY",
        docs_url="https://docs.litellm.ai/docs/simple_proxy",
        integration_tier="gateway",
        description="连接自建 LiteLLM Proxy；Yotsuba Ink 仍负责阶段、预算、恢复与写回。",
    ),
    ProviderTemplate(
        id="portkey-gateway-text",
        label="Portkey AI Gateway",
        kind="openai-compatible",
        base_url="https://api.portkey.ai/v1",
        default_model="",
        api_key_env="PORTKEY_API_KEY",
        docs_url="https://github.com/Portkey-AI/gateway",
        integration_tier="gateway",
        description="Portkey 网关入口；模型路由和附加 Header 需与网关配置保持一致。",
    ),
)
